name: with-location
version: 0.1.0
synopsis: Use ImplicitParams-based source locations in a backward compatible way
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/with-location
category: Data

ghc-options: -Wall

dependencies: base == 4.*

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - with-location
